# Parameters for the global costmap

# Common parameters
common:
  update_frequency: 1.0   # Update frequency in Hz
  publish_frequency: 1.0  # Publish frequency in Hz
  width: 30.0             # Width of the costmap in meters
  height: 30.0            # Height of the costmap in meters
  resolution: 0.05        # Map resolution in meters per pixel

# Parameters specific to the global costmap
global_costmap:
  global_frame: map        # Frame ID for the global map
  robot_base_frame: base_link  # Frame ID for the robot's base
  static_map: true         # Whether to use a static map
  # Adjust the origin of the global costmap
  origin_x: -100.0  # Specify the desired x-coordinate in the map frame
  origin_y: 0.0  # Specify the desired y-coordinate in the map frame
  origin_z: 0.0                   # Typically, set to 0 as height in 2D navigation is on the same plane


# Additional parameters can be added based on specific requirements
