left_wheel_joint_controller:
  type: "velocity_controllers/JointVelocityController"
  joint_name: "left_wheel_joint"
  pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_feedback:
    sensor_topic: "/left_wheel_encoder"

right_wheel_joint_controller:
  type: "velocity_controllers/JointVelocityController"
  joint_name: "right_wheel_joint"
  pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_feedback:
    sensor_topic: "/right_wheel_encoder"